server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: ${PRODUCT_DB}
    password: ${PRODUCT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
