server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
