server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders_db
    username: ${ORDER_DB}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html